// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once
#include <algorithm>
#include <ostream>
#include <iomanip>
#include <version>
#ifdef __cpp_lib_format
#include <format>
#endif
#include "enum_type.hpp"

namespace test::record {
struct EnumTypes final {
    const ::test::record::EnumType enum_t;
    EnumTypes(::test::record::EnumType enum_t_)
    : enum_t(std::move(enum_t_))
    {}

    friend std::ostream& operator<<(std::ostream& os, EnumTypes const& value);
};


}  // namespace test::record
