// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by PyDjinni from 'record.djinni'
#pragma once

namespace test::record {
enum class EnumType : int {
    FIRST_VALUE,
    SECOND_VALUE,
    THIRD_VALUE
};
}  // namespace test::record
