on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install doc dependencies
        run: pip install "pydjinni" "pydjinni[doc]"
      - name: Build and publish docs
        run: mike deploy --push --update-aliases $(git describe --tag | grep -o '^v\d*.\d*') latest
